language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
deploy:
  provider: heroku
  api_key:
    secure: BFtaVCMyaU0YzYFuBRYnmGf9XGcYKP5SqplJQohuLDBfaZwZtZL6AtFZKTqp5VPUKDvZu5kKL1eJ7CWGEDspkbVOk5xp302K9Zu4KSbkhRLb4kiECg5heyS4Y2hdynwk8sAKGUdoVwUDMDLLZuGMX510k2w4TNI7xd4eu/BpORF9n2CqHEiuXkhcUwaCDa2RoYqjYdsisXC1CeMqiP1nawbMFygYpi3DN4x2jJKH8hf9HOHbFkjddrb4zwjEMFBkK87IMrUomCCtvT+KZ+0/q4NoSExXjGbrjhxRX6NMTRW54xSb01gDs7y3Mfk4S37KLf+9qV8k1iRvHcSAHJx65ee5dD6sAS8Cf9EpfK0p5dD8MUuLmnK00Fo3bMT3LQsApC9sqcfpzCIx24wjRnoRYqONSmhksqUaoaAd8A0xvSTmvgNLecxQiX86v3DkPG07IKLhvi5InGeweAShNv3wXzejlTApHxjbzi98s8g6aT79Tbo5/grF8qrYTD+agmsE+odQypJgcUcOMtFlhu4ZoY0m5An/I075USiCiLsiixQqwXji+h88eQRn1QSKz1cyXrST26ZWdqCC3HVue/A0tVzzIfGtd3vEJ02zoMWpNBpXHMPotUxIqh+ad2VVS/C0r/5ubM+0Huy++YhV753EeHW4EzBODp+FZbzCBV43BvA=
  app: lr-casework-style-guide
  on:
    repo: LandRegistry/casework-style-guide
    branch: master
notifications:
  slack:
    secure: R0MXUWUyxvVDG1Ia7jFKXKdldrwN9bLi4XlwLvXo3y6lSqv/mhMFw6f34vKkfQLF8rcAr2QsbmwIk5sEgWBuvu+imxSAtYw0gpxfVnk+p5mtgfxydru/yVwO4rvdmtBwUpLcTydeWgxDWmYQ2LDnr6bSCHbu9G4OVhdfvtUXW8216kuxkTS5dmzbHlySDvw+em1IB6hxVrOo8Rl9Uxo0O8nS0Vk2xB/zut7+tDezRH+lutclMm7FCSSg2/io9nhtczhypW+kNvLIQI3cs9s+Bk3BX90JDVEGKohimQPFE7zCnRzT8V7yVTt+Rn9DP3TzTiH/qRaiPrUMesFgMU541hjYHdw+lvLh8un0dD3l2rLedf6iKPpU08W3TLdAP116ZYkIFbCUocVQWODjFtSahGe8yHgTbjS/G/35WKP5M0bNtMKUmZKHJQv7rWB63iEgd7gE+tCJXd589wxg7HfdYmdEhYOu7fqrgxj8p1XszALEBNijCtwV/Y9DoqLPs+gQVMOqy5H3hG6Tf0MkYsPg03ZGYwfz7j5Qgxyc3BIz7aCR2ETEyHmI7uvmlOp8B48QxDt/a/aphokbIDj3MIkUINEYpcWmod3YvRJAoKdTQURjM9OO5vank8FPy1E4zGA9XGohpdmafyvg9e9aVDKaRJMgFi1Q7ZYSpHtBepFXH/I=
